-- CRM / clients module: columns expected by Clients controllers and views.
-- init_schema placeholders use generic columns; run this once on existing DBs.

ALTER TABLE `client`
  ADD COLUMN `fname` VARCHAR(255) NULL DEFAULT NULL,
  ADD COLUMN `lname` VARCHAR(255) NULL DEFAULT NULL,
  ADD COLUMN `mobile` VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN `landline` VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN `company` VARCHAR(255) NULL DEFAULT NULL,
  ADD COLUMN `address1` VARCHAR(500) NULL DEFAULT NULL,
  ADD COLUMN `address2` VARCHAR(500) NULL DEFAULT NULL,
  ADD COLUMN `city` VARCHAR(255) NULL DEFAULT NULL,
  ADD COLUMN `state` VARCHAR(255) NULL DEFAULT NULL,
  ADD COLUMN `zip` VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN `country` VARCHAR(255) NULL DEFAULT NULL,
  ADD COLUMN `website` VARCHAR(255) NULL DEFAULT NULL,
  ADD COLUMN `job_title` VARCHAR(255) NULL DEFAULT NULL,
  ADD COLUMN `chat` TINYINT UNSIGNED NULL DEFAULT NULL;

ALTER TABLE `staff_client`
  ADD COLUMN `staff_id` INT UNSIGNED NULL DEFAULT NULL,
  ADD COLUMN `client_id` INT UNSIGNED NULL DEFAULT NULL;

ALTER TABLE `client_comment`
  ADD COLUMN `client_id` INT UNSIGNED NULL DEFAULT NULL,
  ADD COLUMN `admin_id` INT UNSIGNED NULL DEFAULT NULL,
  ADD COLUMN `emp_id` INT UNSIGNED NULL DEFAULT NULL,
  ADD COLUMN `comment` TEXT NULL,
  ADD COLUMN `documents` VARCHAR(255) NULL DEFAULT NULL;
