CREATE DATABASE IF NOT EXISTS `kodexcc` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `kodexcc`;

CREATE TABLE IF NOT EXISTS `agenda` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `analytic` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `city` VARCHAR(255) NULL,
  `country` VARCHAR(255) NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `loc` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `postal` VARCHAR(255) NULL,
  `product_id` INT NULL,
  `region` VARCHAR(255) NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `assign_client` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `batch_count_sheet` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `batch_register` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `cart` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `category` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `category_name` VARCHAR(255) NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `sort` INT NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `circular_action` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `circular_internal_audit` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `circular_internal_audit_list` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `circular_internal_audit_result` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `circular_management_review` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `circular_relation` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `client` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `client_comment` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `client_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `complaint` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `complaint_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `config` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `conformance` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `conformance_relation` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `coupon` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `cpd_mailer` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `department` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `document_calibration` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `document_calibration_reocrd` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `document_field_executive_duty` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `document_library` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `document_library_record` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `document_nc_closure` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `document_nc_closure_record` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `document_preventive_maintenance` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `document_preventive_maintenance_record` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `document_receive_inspection` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `duro_order` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `email_template` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `feedback` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `addedby` VARCHAR(255) NULL,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `company_name` VARCHAR(255) NULL,
  `contact` VARCHAR(50) NULL,
  `created` DATETIME NULL,
  `customer_name` VARCHAR(255) NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `feedback` TEXT NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `sample_given` VARCHAR(255) NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `format_internal_audit_plan` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hr_appraisal_form` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hr_appraisal_form_record` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hr_during_leave` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hr_during_leave_record` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hr_format_evaluation_employe_record` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hr_format_evaluation_employee` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hr_format_training_calendar` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hr_format_training_calendar_record` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hr_new_joining_detail` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hr_performance_feedback` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hr_report_organization` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hr_training_attendance` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hr_training_attendance_record` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hr_training_need_assessment` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hr_training_need_assessment_record` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `lab_assign` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `lab_file` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `label` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `label_category` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `label_stock` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `login_history` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `mailer` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `material` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `material_order` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `napp_user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `lname` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `nata_category` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `nata_event` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `notification` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `order_product` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `package_stock` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `payment_setup` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `permission` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `po_order` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `po_order_detail` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `product` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `product_type` VARCHAR(255) NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `production_report` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `project` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `purchase` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `purchase_requirement` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `question` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `question_submit` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `reward_point` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `reward_product` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `reward_user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sale_notification` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sale_question` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sale_reminder` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sale_rep` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sale_report` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `salemeet` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `addedby` VARCHAR(255) NULL,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `company_name` VARCHAR(255) NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `existing` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `interest` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `location` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `occupation` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `service` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sheet_task` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `column_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_cate_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sheet_task_create` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sheet_task_reminder` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sheet_task_track` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `shop_cart` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ss_client_comment` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ss_comment` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ss_document` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ss_sheet_category` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ss_sheet_column` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ss_sheet_data` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ss_sheet_share` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `staff` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `staff_client` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `subcategory` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `subscriber` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `task_comment` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `is_receive_smartsheet` INT NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `user_answer` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `user_permission` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `voc_certificate` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_session_id` INT NULL,
  `category_id` INT NULL,
  `created` DATETIME NULL,
  `description` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `modified` DATETIME NULL,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `session_id` INT NULL,
  `sheet_id` INT NULL,
  `slug` VARCHAR(255) NULL,
  `status` INT NULL,
  `task_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
